#!/bin/bash
# Seed YAMS with ~500 fake memories across multiple projects
API_KEY="yams_5I-0md8QHt21-RxMp1RgcIJhjmACUTfUqByOjHU1UWY"
BASE="http://127.0.0.1:3333"

PROJECTS=(
  "github.com/acme/webapp"
  "github.com/acme/api-gateway"
  "github.com/acme/mobile-app"
  "github.com/acme/infra"
  "github.com/acme/design-system"
  "github.com/acme/data-pipeline"
  "github.com/acme/auth-service"
  "github.com/acme/billing"
  "github.com/acme/docs"
  "github.com/acme/cli-tools"
  "github.com/personal/dotfiles"
  "github.com/personal/blog"
  "gitlab.com/client/ecommerce"
  "gitlab.com/client/dashboard"
  "dev.azure.com/contoso/platform/_git/identity-service"
  "dev.azure.com/contoso/platform/_git/notification-hub"
  "dev.azure.com/contoso/data/_git/etl-pipeline"
  "dev.azure.com/northwind/webshop/_git/checkout-api"
  "dev.azure.com/northwind/webshop/_git/product-catalog"
  ""
)

SCOPES=("session" "session" "session" "project" "project" "global")

MEMORIES=(
  "React useEffect cleanup runs before re-render when deps change, not on unmount only"
  "PostgreSQL EXPLAIN ANALYZE shows actual row counts vs estimates for query tuning"
  "The CSS gap property works in flexbox across all modern browsers now"
  "Docker multi-stage builds reduce final image size by discarding build dependencies"
  "TypeScript satisfies operator validates types without widening the inferred type"
  "Redis SCAN is preferred over KEYS in production to avoid blocking the event loop"
  "Next.js app router server components cannot use useState or useEffect"
  "GraphQL DataLoader batches and deduplicates database queries within a single request"
  "Terraform state locking with DynamoDB prevents concurrent apply operations"
  "Kubernetes liveness probes should not check downstream dependencies"
  "The git reflog keeps entries for 90 days by default even after branch deletion"
  "Prisma raw queries need $queryRaw tagged template to prevent SQL injection"
  "Vite HMR boundary needs to accept itself for CSS modules to hot reload"
  "AWS Lambda cold starts are worse with larger packages and VPC configuration"
  "Zod discriminated unions parse faster than regular unions with .parse()"
  "Python dataclasses with frozen=True are hashable and can be used as dict keys"
  "Nginx try_files directive checks paths in order and serves the first match"
  "WebSocket connections bypass CORS entirely — origin validation must be manual"
  "Go context.WithTimeout automatically cancels child goroutines on deadline"
  "The package-lock.json integrity field uses SHA-512 for subresource integrity"
  "ESLint flat config in eslint.config.js replaces .eslintrc in v9+"
  "Tailwind JIT mode generates CSS on demand so unused classes cost nothing"
  "PostgreSQL partial indexes only index rows matching a WHERE clause"
  "React Server Components can import client components but not vice versa"
  "GitHub Actions concurrency groups cancel redundant workflow runs on push"
  "The Temporal API replaces moment.js for timezone-aware date arithmetic"
  "SQLite WAL mode allows concurrent reads during writes for better throughput"
  "Bun test runner uses describe/it/expect like Jest but runs 10x faster"
  "CSS container queries let components respond to parent size not viewport"
  "Node.js streams backpressure prevents memory exhaustion on large file processing"
  "Rust ownership rules prevent data races at compile time with zero runtime cost"
  "The OpenAPI 3.1 spec aligns with JSON Schema Draft 2020-12"
  "Docker Compose watch mode auto-rebuilds on file changes for development"
  "React 19 useOptimistic enables instant UI updates before server confirmation"
  "Playwright test.step() groups related assertions for better error reporting"
  "FastAPI dependency injection resolves the entire chain before handler runs"
  "GitHub branch protection rules can require specific status checks to pass"
  "The crypto.subtle API provides native browser encryption without libraries"
  "PostgreSQL JSONB GIN indexes speed up containment queries on JSON columns"
  "Kubernetes HPA custom metrics can scale on queue depth not just CPU"
  "TypeScript const assertions narrow literal types to their exact values"
  "Redis pub/sub messages are fire-and-forget — missed if no subscriber is active"
  "Vitest workspace mode runs tests across multiple projects in a monorepo"
  "The HTTP 103 Early Hints header lets browsers preload resources before response"
  "Cloudflare Workers KV is eventually consistent with a 60-second propagation delay"
  "React useDeferredValue delays re-rendering expensive components during fast input"
  "Go generics constraints with comparable allow using types as map keys"
  "Caddy auto-provisions HTTPS certificates from Let's Encrypt with zero config"
  "The AbortController API cleanly cancels fetch requests and event listeners"
  "PostgreSQL advisory locks are application-level locks useful for job queues"
  "Svelte 5 runes replace reactive declarations with explicit $state and $derived"
  "AWS S3 presigned URLs expire and should be generated server-side only"
  "Deno KV provides built-in key-value storage without external dependencies"
  "The View Transitions API enables animated page transitions in SPAs and MPAs"
  "MongoDB change streams push real-time updates without polling the database"
  "Astro islands architecture only hydrates interactive components on the client"
  "Git worktrees allow multiple branches checked out simultaneously from one repo"
  "The Intersection Observer API is more performant than scroll event listeners"
  "Drizzle ORM generates zero-abstraction SQL with full TypeScript type safety"
  "Kubernetes network policies default-deny all traffic when no policy exists"
  "React.lazy with Suspense code-splits components and shows fallback while loading"
  "PostgreSQL CTEs with MATERIALIZED hint prevent the optimizer from inlining"
  "GitHub Copilot context window is limited — smaller focused files get better suggestions"
  "The structuredClone API deep copies objects including Dates and RegExps"
  "Cloudflare R2 is S3-compatible but has zero egress fees"
  "htmx hx-swap-oob updates elements outside the target for multi-region updates"
  "Bun.serve handles WebSocket upgrades inline without a separate ws package"
  "CSS @layer controls specificity order regardless of source code position"
  "Redis streams provide persistent message queues with consumer group support"
  "The URLPattern API matches URL patterns on the server and in service workers"
  "Turso replicates SQLite to edge locations for low-latency reads globally"
  "React useTransition marks updates as non-urgent to keep the UI responsive"
  "Go embed directive bundles static files into the compiled binary"
  "PostgreSQL row-level security policies filter data per-user transparently"
  "The Compression Streams API gzips data in the browser without libraries"
  "Fly.io auto-scaling uses machines that hibernate when idle to save costs"
  "SvelteKit form actions process submissions server-side without client JavaScript"
  "Biome replaces both ESLint and Prettier as a single fast linter and formatter"
  "The Popover API provides native popovers without JavaScript positioning libraries"
  "Neon database branches create instant copies of PostgreSQL for development"
  "Solid.js fine-grained reactivity updates only the exact DOM nodes that changed"
  "Edge functions run in V8 isolates with sub-millisecond cold starts"
  "CSS @scope limits styles to a DOM subtree without BEM or modules"
  "Hono middleware runs in order and c.set/c.get shares state through the chain"
  "The Navigation API replaces history.pushState with a modern async interface"
  "PlanetScale database branching enables schema changes without downtime"
  "Qwik resumability skips hydration entirely by serializing the component tree"
  "PostgreSQL LISTEN/NOTIFY provides lightweight pub/sub without external brokers"
  "The Reporting API captures browser errors and deprecations automatically"
  "Remix nested routes colocate data loading with UI components for waterfalls"
  "WASM components enable sandboxed plugin systems with near-native performance"
  "CSS :has() selector enables parent styling based on child element state"
  "Durable Objects provide strongly consistent single-threaded state at the edge"
  "The EyeDropper API lets users pick colors from anywhere on their screen"
  "tRPC provides end-to-end type safety between client and server without codegen"
  "SQLite JSON functions can query nested fields without extracting to columns"
  "Bun macros run at bundle time and inline the result as constants"
  "The Sanitizer API safely inserts HTML without XSS through browser-native sanitization"
  "Supabase realtime channels multiplex PostgreSQL changes over a single WebSocket"
  "Zod transform chains let you parse, validate, and reshape data in one pipeline"
  "CSS subgrid allows children to participate in their grandparent grid layout"
  "Nitro server engine powers both Nuxt and Analog with universal deployment"
  "The Barcode Detection API reads QR codes natively without scanning libraries"
  "Turbopack incremental computation reuses previous build results for faster rebuilds"
  "Fresh islands architecture in Deno only ships JavaScript for interactive components"
  "PostgreSQL generated columns compute values automatically on insert or update"
  "The Web Locks API coordinates access to shared resources across browser tabs"
  "SST Ion uses Pulumi under the hood for infrastructure as code on AWS"
  "Million.js block virtual DOM skips diffing with compiler-optimized static analysis"
  "CSS anchor positioning ties popovers and tooltips to trigger elements declaratively"
  "Effect-TS provides structured concurrency with typed errors and dependency injection"
  "The Credential Management API streamlines login flows with native browser UI"
  "PartyKit provides real-time collaboration primitives using Cloudflare Durable Objects"
  "Alpine.js x-data scopes reactivity to DOM elements without a build step"
  "PostgreSQL table partitioning splits large tables for faster queries on time-series data"
  "The File System Access API allows web apps to read and write local files"
  "Convex replaces your backend with reactive queries that push updates automatically"
  "Preact Signals provide fine-grained reactivity outside of component boundaries"
  "CSS color-mix() blends two colors in any color space including oklch"
  "Encore.ts generates API documentation and clients from TypeScript type definitions"
  "The Web Share API triggers the native OS share sheet from web applications"
  "Payload CMS 3.0 runs as Next.js middleware for seamless full-stack integration"
  "Zustand selectors with shallow equality checks prevent unnecessary re-renders"
  "PostgreSQL exclusion constraints prevent overlapping ranges in scheduling systems"
  "The WebGPU API provides GPU compute access for ML inference in the browser"
  "Tanstack Router provides file-based routing with full type safety for search params"
  "Bun.password.hash uses Argon2id by default which resists GPU cracking attacks"
  "CSS scroll-driven animations trigger on scroll progress without JavaScript"
  "Electric SQL syncs SQLite between client and server for local-first applications"
  "The Launch Handler API controls how PWAs open from links and shortcuts"
  "Panda CSS generates atomic styles at build time from a type-safe API"
  "Zig comptime evaluates expressions at compile time eliminating runtime overhead"
  "PostgreSQL MERGE statement combines insert, update, and delete in a single operation"
  "The Web Transport API enables low-latency bidirectional communication over HTTP/3"
  "Vinxi is the full-stack JavaScript SDK that powers SolidStart and TanStack Start"
  "React compiler automatically memoizes components removing the need for useMemo"
  "CSS text-wrap: balance distributes text evenly across lines in headings"
  "Val Town lets you deploy serverless functions from the browser as vals"
  "The Web Authentication API enables passwordless login with passkeys and biometrics"
  "Leptos provides Rust full-stack web development with fine-grained reactivity"
  "PostgreSQL BRIN indexes are compact and efficient for naturally ordered data like timestamps"
  "The Background Sync API retries failed network requests when connectivity returns"
  "Tauri 2.0 supports mobile platforms using platform-native webviews instead of Electron"
  "Nuxt server routes in /server/api auto-register as API endpoints"
  "CSS @starting-style enables transitions on elements entering the DOM"
  "Workers AI runs inference models on Cloudflare edge network without GPU provisioning"
  "The ContentVisibility API defers rendering of off-screen content for performance"
  "Drizzle relations define table relationships for type-safe joins without an ORM"
  "HTMX boosted links progressively enhance regular anchors with AJAX navigation"
  "PostgreSQL triggers on TRUNCATE fire once per statement not per row"
  "The Shared Storage API provides cross-site storage without third-party cookies"
  "Coolify is a self-hosted Heroku alternative that deploys from Git with Docker"
  "SWC is 20x faster than Babel for TypeScript transpilation"
  "CSS light-dark() function returns values based on the color scheme automatically"
  "OpenTelemetry auto-instrumentation traces HTTP requests across service boundaries"
  "The Document Picture-in-Picture API shows arbitrary HTML in a floating window"
  "Wasp lang generates full-stack React + Node apps from a declarative DSL"
  "Bun shell $-backtick provides cross-platform shell scripting with JavaScript interop"
  "PostgreSQL COPY is 10-100x faster than INSERT for bulk data loading"
  "The Storage Buckets API separates ephemeral and persistent browser storage"
  "Expo Router provides file-based navigation for React Native with deep linking"
  "CSS math functions like min() max() clamp() enable fluid responsive design"
  "Supabase Edge Functions run Deno on Fly.io close to your Postgres database"
  "The FedCM API provides federated identity flows without redirect-based sign-in"
  "Nitropack pre-rendering generates static HTML for dynamic Nuxt routes at build time"
  "Solid Router createAsync integrates Suspense with route data loading"
  "PostgreSQL check constraints can reference multiple columns for complex validation"
  "The Speculation Rules API tells the browser which pages to prerender next"
  "Capacitor bridges web apps to native APIs for cross-platform mobile deployment"
  "CSS math functions calc() round() mod() perform computations on custom properties"
  "Lucia auth provides session management without the complexity of next-auth"
  "The Fenced Frames API isolates embedded content for privacy without iframes"
  "Storybook Component Story Format co-locates stories with component source files"
  "Zig build system replaces Make and CMake for C/C++ project compilation"
  "PostgreSQL pg_stat_statements tracks query performance statistics for optimization"
  "The Web MIDI API enables real-time musical instrument communication in browsers"
  "Leptos server functions serialize Rust types for seamless client-server communication"
  "Docker buildx bake builds multiple images in parallel from a compose file"
  "CSS nesting is now native in browsers without needing Sass or PostCSS"
  "Wrangler dev proxies requests to remote Cloudflare services for local testing"
  "The Digital Goods API handles in-app purchases for PWAs in app stores"
  "Gleam on BEAM provides type-safe functional programming with Erlang interop"
  "PostgreSQL VACUUM ANALYZE reclaims dead rows and updates planner statistics"
  "The Compute Pressure API reports CPU utilization for adaptive media quality"
  "Remix single fetch reduces waterfall requests by batching all loader calls"
  "D1 is Cloudflare's edge SQLite database with automatic replication"
  "CSS @property defines custom properties with types for animatable transitions"
  "Arc browser custom boosts inject CSS and JavaScript into any website"
  "The Web Codecs API provides low-level access to video and audio encoders"
  "Astro content collections validate frontmatter with Zod schemas at build time"
  "Bun bundler tree-shakes ESM and CommonJS with package.json sideEffects support"
  "PostgreSQL unnest expands arrays into rows for set-returning operations"
  "The Multi-Screen Window Placement API positions windows across multiple monitors"
  "Rspack is a Rust-based webpack-compatible bundler that is 5-10x faster"
  "Nitro auto-imports composables and utils without explicit import statements"
  "CSS @font-face size-adjust prevents layout shift when swapping web fonts"
  "Infisical provides open-source secrets management with automatic rotation"
  "The WebNN API runs neural network inference using OS-level ML accelerators"
  "SolidStart server$ creates inline server functions without separate API routes"
  "PostgreSQL CREATE DOMAIN defines reusable column types with constraints"
  "The Local Font Access API enumerates installed fonts for design applications"
  "Tauri IPC uses JSON-RPC for structured communication between Rust and JavaScript"
)

total=${#MEMORIES[@]}
count=0
errors=0
BATCH_SIZE=10

echo "Seeding $total memory templates across ${#PROJECTS[@]} projects..."

for mem in "${MEMORIES[@]}"; do
  # Pick random project and scope
  project=${PROJECTS[$((RANDOM % ${#PROJECTS[@]}))]}
  scope=${SCOPES[$((RANDOM % ${#SCOPES[@]}))]}

  # Build JSON payload
  if [ -z "$project" ]; then
    payload=$(printf '{"summary":"%s","scope":"%s"}' "$mem" "$scope")
  else
    payload=$(printf '{"summary":"%s","git_remote":"%s","scope":"%s"}' "$mem" "$project" "$scope")
  fi

  curl -s -X POST "$BASE/ingest" \
    -H "Authorization: Bearer $API_KEY" \
    -H "Content-Type: application/json" \
    -d "$payload" > /dev/null 2>&1 &

  count=$((count + 1))

  # Run in batches to avoid overwhelming Ollama
  if (( count % BATCH_SIZE == 0 )); then
    wait
    echo "  $count / $total ingested..."
  fi
done

wait
echo "Done! Ingested $count memories."
